database:
  host: example.com
  port: 8080
  user: example_value
  password: your_password_here
  database: your_database_name
  echo: true_or_false

app:
  log_level: info

jwt:
  secret: your_jwt_secret
  expire_minutes: 60